from .abstract_hook import AbstractHook
from ..nets.abstract_net import AbstractNet

import numpy as np
import rethinkdb as r

from datetime import datetime
import json
import logging
from os import path
import pytz


class RethinkDBHook(AbstractHook):
    """
    Stores the training configuration and progress to RethinkDB.

    The config is stored in `setups` database as raw JSON. Each epoch is stored in `training` database as raw JSON
    with "foreign" index to `setups` document."""

    def __init__(self, net: AbstractNet, config: dict, credentials_file: str, **kwargs):
        """
        Save training config to database `setups`. Save the unique id generated by the database.
        :param net: trained network
        :param config: the whole configuration file
        :param credentials_file: path to JSON credentials file which contains fields: host, port, user, password, db.
                                 This file should not be included in git.
        """

        super().__init__(net=net, config=config, **kwargs)
        with open(credentials_file, 'r') as f:
            self._credentials = json.load(f)

        logging.debug('Creating setup in the db')
        with r.connect(**self._credentials) as conn:
            response = r.table('setups')\
                        .insert({**config,
                                 **{'timestamp': r.expr(datetime.now(pytz.utc))},
                                 })\
                        .run(conn)
            if response['errors'] > 0:
                logging.error('Error: %s', response['errors'])
                return
            if response['inserted'] != 1:
                logging.error('Inserted unexpected number of documents: %s', response['inserted'])
                return
            self._rethink_id = response['generated_keys'][0]
            logging.debug('Created setup: %s', self._rethink_id)

        with open(path.join(net.log_dir, 'rethink_key.json'), 'w') as f:
            json.dump({'rethink_id': self._rethink_id}, f)

    def before_first_epoch(self, valid_results: dict, test_results: dict = None, **kwargs) -> None:
        logging.debug('Rethink: before first epoch')

        with r.connect(**self._credentials) as conn:

            item = {'timestamp': r.expr(datetime.now(pytz.utc)),
                    'setup_id': self._rethink_id,
                    'epoch_id': 0,
                    **{'valid_{}'.format(key): (value.tolist() if isinstance(value, np.ndarray) else value)
                       for key, value in valid_results.items()},
                    **{'test_{}'.format(key): (value.tolist() if isinstance(value, np.ndarray) else value)
                       for key, value in test_results.items()}
                    }

            response = r.table('training')\
                        .insert(item)\
                        .run(conn)
            if response['errors'] > 0:
                logging.error('Error: %s', response['errors'])
                return
            if response['inserted'] != 1:
                logging.error('Inserted unexpected number of documents: %s', response['inserted'])
                return
            progress_rethink_id = response['generated_keys'][0]
            logging.debug('Created train. progress: %s', progress_rethink_id)

    def after_epoch(self, epoch_id: int, train_results: dict, valid_results: dict, test_results: dict=None,
                    **kwargs) -> None:
        logging.info('Rethink: after epoch %d', epoch_id)

        with r.connect(**self._credentials) as conn:
            item = {'timestamp': r.expr(datetime.now(pytz.utc)),
                    'setup_id': self._rethink_id,
                    'epoch_id': epoch_id,
                    ** {'train_{}'.format(key): (value.tolist() if isinstance(value, np.ndarray) else value)
                        for key, value in train_results.items()},
                    **{'valid_{}'.format(key): (value.tolist() if isinstance(value, np.ndarray) else value)
                       for key, value in valid_results.items()},
                    **{'test_{}'.format(key): (value.tolist() if isinstance(value, np.ndarray) else value)
                       for key, value in test_results.items()},
                    }

            response = r.table('training')\
                        .insert(item)\
                        .run(conn)
            if response['errors'] > 0:
                logging.error('Error: %s', response['errors'])
                return
            if response['inserted'] != 1:
                logging.error('Inserted unexpected number of documents: %s', response['inserted'])
                return
            progress_rethink_id = response['generated_keys'][0]
            logging.debug('Created train. progress: %s', progress_rethink_id)
